#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frontend.DBML
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="School-Live")]
	public partial class SchoolDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertComParameter(ComParameter instance);
    partial void UpdateComParameter(ComParameter instance);
    partial void DeleteComParameter(ComParameter instance);
    partial void InsertBL_Audit(BL_Audit instance);
    partial void UpdateBL_Audit(BL_Audit instance);
    partial void DeleteBL_Audit(BL_Audit instance);
    partial void InsertYearDefination(YearDefination instance);
    partial void UpdateYearDefination(YearDefination instance);
    partial void DeleteYearDefination(YearDefination instance);
    partial void InsertFees_Collection(Fees_Collection instance);
    partial void UpdateFees_Collection(Fees_Collection instance);
    partial void DeleteFees_Collection(Fees_Collection instance);
    partial void InsertcDocumentNumber(cDocumentNumber instance);
    partial void UpdatecDocumentNumber(cDocumentNumber instance);
    partial void DeletecDocumentNumber(cDocumentNumber instance);
    partial void InsertFees_Assignment(Fees_Assignment instance);
    partial void UpdateFees_Assignment(Fees_Assignment instance);
    partial void DeleteFees_Assignment(Fees_Assignment instance);
    partial void InsertStudent_Profile(Student_Profile instance);
    partial void UpdateStudent_Profile(Student_Profile instance);
    partial void DeleteStudent_Profile(Student_Profile instance);
    partial void InsertFees_Open(Fees_Open instance);
    partial void UpdateFees_Open(Fees_Open instance);
    partial void DeleteFees_Open(Fees_Open instance);
    #endregion
		
		public SchoolDBDataContext() : 
				base(global::Frontend.Properties.Settings.Default.DatabaseConnection, mappingSource)
		{
			OnCreated();
		}
		
		public SchoolDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchoolDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchoolDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchoolDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ComParameterType> ComParameterTypes
		{
			get
			{
				return this.GetTable<ComParameterType>();
			}
		}
		
		public System.Data.Linq.Table<ComParameter> ComParameters
		{
			get
			{
				return this.GetTable<ComParameter>();
			}
		}
		
		public System.Data.Linq.Table<BL_Audit> BL_Audits
		{
			get
			{
				return this.GetTable<BL_Audit>();
			}
		}
		
		public System.Data.Linq.Table<YearDefination> YearDefinations
		{
			get
			{
				return this.GetTable<YearDefination>();
			}
		}
		
		public System.Data.Linq.Table<Fees_Collection> Fees_Collections
		{
			get
			{
				return this.GetTable<Fees_Collection>();
			}
		}
		
		public System.Data.Linq.Table<cDocumentNumber> cDocumentNumbers
		{
			get
			{
				return this.GetTable<cDocumentNumber>();
			}
		}
		
		public System.Data.Linq.Table<Fees_Assignment> Fees_Assignments
		{
			get
			{
				return this.GetTable<Fees_Assignment>();
			}
		}
		
		public System.Data.Linq.Table<Student_Profile> Student_Profiles
		{
			get
			{
				return this.GetTable<Student_Profile>();
			}
		}
		
		public System.Data.Linq.Table<Fees_Open> Fees_Opens
		{
			get
			{
				return this.GetTable<Fees_Open>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ComParameterType")]
	public partial class ComParameterType
	{
		
		private System.Nullable<long> _Id;
		
		private string _Description;
		
		private bool _Status;
		
		private System.Nullable<bool> _IsBranchLevel;
		
		private System.Nullable<bool> _IsParent;
		
		public ComParameterType()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsBranchLevel", DbType="Bit")]
		public System.Nullable<bool> IsBranchLevel
		{
			get
			{
				return this._IsBranchLevel;
			}
			set
			{
				if ((this._IsBranchLevel != value))
				{
					this._IsBranchLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsParent", DbType="Bit")]
		public System.Nullable<bool> IsParent
		{
			get
			{
				return this._IsParent;
			}
			set
			{
				if ((this._IsParent != value))
				{
					this._IsParent = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ComParameters")]
	public partial class ComParameter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Description;
		
		private long _Type;
		
		private System.Nullable<int> _CurrentStatusId;
		
		private System.Nullable<long> _BranchId;
		
		private bool _Status;
		
		private string _Remarks;
		
		private System.Nullable<int> _ParentId;
		
		private string _Code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnTypeChanging(long value);
    partial void OnTypeChanged();
    partial void OnCurrentStatusIdChanging(System.Nullable<int> value);
    partial void OnCurrentStatusIdChanged();
    partial void OnBranchIdChanging(System.Nullable<long> value);
    partial void OnBranchIdChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnParentIdChanging(System.Nullable<int> value);
    partial void OnParentIdChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    #endregion
		
		public ComParameter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="BigInt NOT NULL")]
		public long Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentStatusId", DbType="Int")]
		public System.Nullable<int> CurrentStatusId
		{
			get
			{
				return this._CurrentStatusId;
			}
			set
			{
				if ((this._CurrentStatusId != value))
				{
					this.OnCurrentStatusIdChanging(value);
					this.SendPropertyChanging();
					this._CurrentStatusId = value;
					this.SendPropertyChanged("CurrentStatusId");
					this.OnCurrentStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchId", DbType="BigInt")]
		public System.Nullable<long> BranchId
		{
			get
			{
				return this._BranchId;
			}
			set
			{
				if ((this._BranchId != value))
				{
					this.OnBranchIdChanging(value);
					this.SendPropertyChanging();
					this._BranchId = value;
					this.SendPropertyChanged("BranchId");
					this.OnBranchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(1000)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int")]
		public System.Nullable<int> ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this.OnParentIdChanging(value);
					this.SendPropertyChanging();
					this._ParentId = value;
					this.SendPropertyChanged("ParentId");
					this.OnParentIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BL_Audit")]
	public partial class BL_Audit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _Id;
		
		private int _Action_Id;
		
		private System.DateTime _Action_Date;
		
		private string _User_Id;
		
		private string _IP;
		
		private string _Doc_Id;
		
		private string _Doc_Name;
		
		private decimal _Master_Id;
		
		private decimal _Detail_Id;
		
		private int _BranchId;
		
		private string _Remarks;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(decimal value);
    partial void OnIdChanged();
    partial void OnAction_IdChanging(int value);
    partial void OnAction_IdChanged();
    partial void OnAction_DateChanging(System.DateTime value);
    partial void OnAction_DateChanged();
    partial void OnUser_IdChanging(string value);
    partial void OnUser_IdChanged();
    partial void OnIPChanging(string value);
    partial void OnIPChanged();
    partial void OnDoc_IdChanging(string value);
    partial void OnDoc_IdChanged();
    partial void OnDoc_NameChanging(string value);
    partial void OnDoc_NameChanged();
    partial void OnMaster_IdChanging(decimal value);
    partial void OnMaster_IdChanged();
    partial void OnDetail_IdChanging(decimal value);
    partial void OnDetail_IdChanged();
    partial void OnBranchIdChanging(int value);
    partial void OnBranchIdChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    #endregion
		
		public BL_Audit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action_Id", DbType="Int NOT NULL")]
		public int Action_Id
		{
			get
			{
				return this._Action_Id;
			}
			set
			{
				if ((this._Action_Id != value))
				{
					this.OnAction_IdChanging(value);
					this.SendPropertyChanging();
					this._Action_Id = value;
					this.SendPropertyChanged("Action_Id");
					this.OnAction_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Action_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Action_Date
		{
			get
			{
				return this._Action_Date;
			}
			set
			{
				if ((this._Action_Date != value))
				{
					this.OnAction_DateChanging(value);
					this.SendPropertyChanging();
					this._Action_Date = value;
					this.SendPropertyChanged("Action_Date");
					this.OnAction_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string IP
		{
			get
			{
				return this._IP;
			}
			set
			{
				if ((this._IP != value))
				{
					this.OnIPChanging(value);
					this.SendPropertyChanging();
					this._IP = value;
					this.SendPropertyChanged("IP");
					this.OnIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Id", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Doc_Id
		{
			get
			{
				return this._Doc_Id;
			}
			set
			{
				if ((this._Doc_Id != value))
				{
					this.OnDoc_IdChanging(value);
					this.SendPropertyChanging();
					this._Doc_Id = value;
					this.SendPropertyChanged("Doc_Id");
					this.OnDoc_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Doc_Name
		{
			get
			{
				return this._Doc_Name;
			}
			set
			{
				if ((this._Doc_Name != value))
				{
					this.OnDoc_NameChanging(value);
					this.SendPropertyChanging();
					this._Doc_Name = value;
					this.SendPropertyChanged("Doc_Name");
					this.OnDoc_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Master_Id", DbType="Decimal(18,0) NOT NULL")]
		public decimal Master_Id
		{
			get
			{
				return this._Master_Id;
			}
			set
			{
				if ((this._Master_Id != value))
				{
					this.OnMaster_IdChanging(value);
					this.SendPropertyChanging();
					this._Master_Id = value;
					this.SendPropertyChanged("Master_Id");
					this.OnMaster_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail_Id", DbType="Decimal(18,0) NOT NULL")]
		public decimal Detail_Id
		{
			get
			{
				return this._Detail_Id;
			}
			set
			{
				if ((this._Detail_Id != value))
				{
					this.OnDetail_IdChanging(value);
					this.SendPropertyChanging();
					this._Detail_Id = value;
					this.SendPropertyChanged("Detail_Id");
					this.OnDetail_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchId", DbType="Int NOT NULL")]
		public int BranchId
		{
			get
			{
				return this._BranchId;
			}
			set
			{
				if ((this._BranchId != value))
				{
					this.OnBranchIdChanging(value);
					this.SendPropertyChanging();
					this._BranchId = value;
					this.SendPropertyChanged("BranchId");
					this.OnBranchIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(8000)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.YearDefination")]
	public partial class YearDefination : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.DateTime _FromDate;
		
		private System.Nullable<System.DateTime> _ToDate;
		
		private string _YearName;
		
		private System.Nullable<int> _CurrentStatusId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnFromDateChanging(System.DateTime value);
    partial void OnFromDateChanged();
    partial void OnToDateChanging(System.Nullable<System.DateTime> value);
    partial void OnToDateChanged();
    partial void OnYearNameChanging(string value);
    partial void OnYearNameChanged();
    partial void OnCurrentStatusIdChanging(System.Nullable<int> value);
    partial void OnCurrentStatusIdChanged();
    #endregion
		
		public YearDefination()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromDate", DbType="DateTime NOT NULL")]
		public System.DateTime FromDate
		{
			get
			{
				return this._FromDate;
			}
			set
			{
				if ((this._FromDate != value))
				{
					this.OnFromDateChanging(value);
					this.SendPropertyChanging();
					this._FromDate = value;
					this.SendPropertyChanged("FromDate");
					this.OnFromDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ToDate
		{
			get
			{
				return this._ToDate;
			}
			set
			{
				if ((this._ToDate != value))
				{
					this.OnToDateChanging(value);
					this.SendPropertyChanging();
					this._ToDate = value;
					this.SendPropertyChanged("ToDate");
					this.OnToDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearName", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string YearName
		{
			get
			{
				return this._YearName;
			}
			set
			{
				if ((this._YearName != value))
				{
					this.OnYearNameChanging(value);
					this.SendPropertyChanging();
					this._YearName = value;
					this.SendPropertyChanged("YearName");
					this.OnYearNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentStatusId", DbType="Int")]
		public System.Nullable<int> CurrentStatusId
		{
			get
			{
				return this._CurrentStatusId;
			}
			set
			{
				if ((this._CurrentStatusId != value))
				{
					this.OnCurrentStatusIdChanging(value);
					this.SendPropertyChanging();
					this._CurrentStatusId = value;
					this.SendPropertyChanged("CurrentStatusId");
					this.OnCurrentStatusIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fees_Collection")]
	public partial class Fees_Collection : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<decimal> _TotalAmount;
		
		private System.Nullable<long> _StId;
		
		private System.Nullable<System.DateTime> _PaidDate;
		
		private System.Nullable<int> _CurrentStatusId;
		
		private string _Remarks;
		
		private System.Nullable<System.DateTime> _ActionDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnTotalAmountChanging(System.Nullable<decimal> value);
    partial void OnTotalAmountChanged();
    partial void OnStIdChanging(System.Nullable<long> value);
    partial void OnStIdChanged();
    partial void OnPaidDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPaidDateChanged();
    partial void OnCurrentStatusIdChanging(System.Nullable<int> value);
    partial void OnCurrentStatusIdChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnActionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnActionDateChanged();
    #endregion
		
		public Fees_Collection()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TotalAmount
		{
			get
			{
				return this._TotalAmount;
			}
			set
			{
				if ((this._TotalAmount != value))
				{
					this.OnTotalAmountChanging(value);
					this.SendPropertyChanging();
					this._TotalAmount = value;
					this.SendPropertyChanged("TotalAmount");
					this.OnTotalAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StId", DbType="BigInt")]
		public System.Nullable<long> StId
		{
			get
			{
				return this._StId;
			}
			set
			{
				if ((this._StId != value))
				{
					this.OnStIdChanging(value);
					this.SendPropertyChanging();
					this._StId = value;
					this.SendPropertyChanged("StId");
					this.OnStIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PaidDate
		{
			get
			{
				return this._PaidDate;
			}
			set
			{
				if ((this._PaidDate != value))
				{
					this.OnPaidDateChanging(value);
					this.SendPropertyChanging();
					this._PaidDate = value;
					this.SendPropertyChanged("PaidDate");
					this.OnPaidDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentStatusId", DbType="Int")]
		public System.Nullable<int> CurrentStatusId
		{
			get
			{
				return this._CurrentStatusId;
			}
			set
			{
				if ((this._CurrentStatusId != value))
				{
					this.OnCurrentStatusIdChanging(value);
					this.SendPropertyChanging();
					this._CurrentStatusId = value;
					this.SendPropertyChanged("CurrentStatusId");
					this.OnCurrentStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ActionDate
		{
			get
			{
				return this._ActionDate;
			}
			set
			{
				if ((this._ActionDate != value))
				{
					this.OnActionDateChanging(value);
					this.SendPropertyChanging();
					this._ActionDate = value;
					this.SendPropertyChanged("ActionDate");
					this.OnActionDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cDocumentNumbers")]
	public partial class cDocumentNumber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nCompanyId;
		
		private string _vcDocumentNumber;
		
		private string _vcLocation;
		
		private int _nFinancialYear;
		
		private int _nSequenceNumber;
		
		private string _vcPrefix;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnCompanyIdChanging(int value);
    partial void OnnCompanyIdChanged();
    partial void OnvcDocumentNumberChanging(string value);
    partial void OnvcDocumentNumberChanged();
    partial void OnvcLocationChanging(string value);
    partial void OnvcLocationChanged();
    partial void OnnFinancialYearChanging(int value);
    partial void OnnFinancialYearChanged();
    partial void OnnSequenceNumberChanging(int value);
    partial void OnnSequenceNumberChanged();
    partial void OnvcPrefixChanging(string value);
    partial void OnvcPrefixChanged();
    #endregion
		
		public cDocumentNumber()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nCompanyId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nCompanyId
		{
			get
			{
				return this._nCompanyId;
			}
			set
			{
				if ((this._nCompanyId != value))
				{
					this.OnnCompanyIdChanging(value);
					this.SendPropertyChanging();
					this._nCompanyId = value;
					this.SendPropertyChanged("nCompanyId");
					this.OnnCompanyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcDocumentNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vcDocumentNumber
		{
			get
			{
				return this._vcDocumentNumber;
			}
			set
			{
				if ((this._vcDocumentNumber != value))
				{
					this.OnvcDocumentNumberChanging(value);
					this.SendPropertyChanging();
					this._vcDocumentNumber = value;
					this.SendPropertyChanged("vcDocumentNumber");
					this.OnvcDocumentNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcLocation", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vcLocation
		{
			get
			{
				return this._vcLocation;
			}
			set
			{
				if ((this._vcLocation != value))
				{
					this.OnvcLocationChanging(value);
					this.SendPropertyChanging();
					this._vcLocation = value;
					this.SendPropertyChanged("vcLocation");
					this.OnvcLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nFinancialYear", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nFinancialYear
		{
			get
			{
				return this._nFinancialYear;
			}
			set
			{
				if ((this._nFinancialYear != value))
				{
					this.OnnFinancialYearChanging(value);
					this.SendPropertyChanging();
					this._nFinancialYear = value;
					this.SendPropertyChanged("nFinancialYear");
					this.OnnFinancialYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nSequenceNumber", DbType="Int NOT NULL")]
		public int nSequenceNumber
		{
			get
			{
				return this._nSequenceNumber;
			}
			set
			{
				if ((this._nSequenceNumber != value))
				{
					this.OnnSequenceNumberChanging(value);
					this.SendPropertyChanging();
					this._nSequenceNumber = value;
					this.SendPropertyChanged("nSequenceNumber");
					this.OnnSequenceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vcPrefix", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vcPrefix
		{
			get
			{
				return this._vcPrefix;
			}
			set
			{
				if ((this._vcPrefix != value))
				{
					this.OnvcPrefixChanging(value);
					this.SendPropertyChanging();
					this._vcPrefix = value;
					this.SendPropertyChanged("vcPrefix");
					this.OnvcPrefixChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fees_Assignment")]
	public partial class Fees_Assignment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _FeeId;
		
		private System.Nullable<long> _StId;
		
		private System.Nullable<System.DateTime> _AssignmentDate;
		
		private System.Nullable<decimal> _OpeningAmount;
		
		private System.Nullable<bool> _IsOpening;
		
		private System.Nullable<int> _CurrentStatusId;
		
		private System.DateTime _ActionDate;
		
		private string _Description;
		
		private System.Nullable<long> _Month;
		
		private System.Nullable<long> _Year;
		
		private string _DocumentNo;
		
		private string _Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnFeeIdChanging(System.Nullable<long> value);
    partial void OnFeeIdChanged();
    partial void OnStIdChanging(System.Nullable<long> value);
    partial void OnStIdChanged();
    partial void OnAssignmentDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAssignmentDateChanged();
    partial void OnOpeningAmountChanging(System.Nullable<decimal> value);
    partial void OnOpeningAmountChanged();
    partial void OnIsOpeningChanging(System.Nullable<bool> value);
    partial void OnIsOpeningChanged();
    partial void OnCurrentStatusIdChanging(System.Nullable<int> value);
    partial void OnCurrentStatusIdChanged();
    partial void OnActionDateChanging(System.DateTime value);
    partial void OnActionDateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnMonthChanging(System.Nullable<long> value);
    partial void OnMonthChanged();
    partial void OnYearChanging(System.Nullable<long> value);
    partial void OnYearChanged();
    partial void OnDocumentNoChanging(string value);
    partial void OnDocumentNoChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    #endregion
		
		public Fees_Assignment()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeId", DbType="BigInt")]
		public System.Nullable<long> FeeId
		{
			get
			{
				return this._FeeId;
			}
			set
			{
				if ((this._FeeId != value))
				{
					this.OnFeeIdChanging(value);
					this.SendPropertyChanging();
					this._FeeId = value;
					this.SendPropertyChanged("FeeId");
					this.OnFeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StId", DbType="BigInt")]
		public System.Nullable<long> StId
		{
			get
			{
				return this._StId;
			}
			set
			{
				if ((this._StId != value))
				{
					this.OnStIdChanging(value);
					this.SendPropertyChanging();
					this._StId = value;
					this.SendPropertyChanged("StId");
					this.OnStIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignmentDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AssignmentDate
		{
			get
			{
				return this._AssignmentDate;
			}
			set
			{
				if ((this._AssignmentDate != value))
				{
					this.OnAssignmentDateChanging(value);
					this.SendPropertyChanging();
					this._AssignmentDate = value;
					this.SendPropertyChanged("AssignmentDate");
					this.OnAssignmentDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpeningAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> OpeningAmount
		{
			get
			{
				return this._OpeningAmount;
			}
			set
			{
				if ((this._OpeningAmount != value))
				{
					this.OnOpeningAmountChanging(value);
					this.SendPropertyChanging();
					this._OpeningAmount = value;
					this.SendPropertyChanged("OpeningAmount");
					this.OnOpeningAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOpening", DbType="Bit")]
		public System.Nullable<bool> IsOpening
		{
			get
			{
				return this._IsOpening;
			}
			set
			{
				if ((this._IsOpening != value))
				{
					this.OnIsOpeningChanging(value);
					this.SendPropertyChanging();
					this._IsOpening = value;
					this.SendPropertyChanged("IsOpening");
					this.OnIsOpeningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentStatusId", DbType="Int")]
		public System.Nullable<int> CurrentStatusId
		{
			get
			{
				return this._CurrentStatusId;
			}
			set
			{
				if ((this._CurrentStatusId != value))
				{
					this.OnCurrentStatusIdChanging(value);
					this.SendPropertyChanging();
					this._CurrentStatusId = value;
					this.SendPropertyChanged("CurrentStatusId");
					this.OnCurrentStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionDate", DbType="DateTime NOT NULL")]
		public System.DateTime ActionDate
		{
			get
			{
				return this._ActionDate;
			}
			set
			{
				if ((this._ActionDate != value))
				{
					this.OnActionDateChanging(value);
					this.SendPropertyChanging();
					this._ActionDate = value;
					this.SendPropertyChanged("ActionDate");
					this.OnActionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="BigInt")]
		public System.Nullable<long> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this.OnMonthChanging(value);
					this.SendPropertyChanging();
					this._Month = value;
					this.SendPropertyChanged("Month");
					this.OnMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="BigInt")]
		public System.Nullable<long> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentNo", DbType="VarChar(50)")]
		public string DocumentNo
		{
			get
			{
				return this._DocumentNo;
			}
			set
			{
				if ((this._DocumentNo != value))
				{
					this.OnDocumentNoChanging(value);
					this.SendPropertyChanging();
					this._DocumentNo = value;
					this.SendPropertyChanged("DocumentNo");
					this.OnDocumentNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student_Profile")]
	public partial class Student_Profile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private string _Name;
		
		private string _CNIC;
		
		private string _FName;
		
		private System.Nullable<System.DateTime> _DateTime;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<long> _StudyClassId;
		
		private System.Nullable<long> _AdmissionClassId;
		
		private System.Nullable<long> _SecId;
		
		private string _Remarks;
		
		private string _GuardianName;
		
		private System.Nullable<long> _GuardianRelationId;
		
		private string _GRNo;
		
		private System.Nullable<long> _ReligionId;
		
		private System.Nullable<long> _CasteId;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private System.Nullable<long> _PlaceOBCityId;
		
		private System.Nullable<long> _LastSchoolId;
		
		private System.Nullable<long> _ProfessionId;
		
		private string _PermAdress;
		
		private string _PermMobileNo;
		
		private string _PermPhoneNo;
		
		private string _PresentAddress;
		
		private string _PresentMobileNo;
		
		private string _PresentPhoneNo;
		
		private string _OfficeAddress;
		
		private string _OfficeMobileNo;
		
		private string _OfficePhoneNo;
		
		private string _Email;
		
		private string _RollNo;
		
		private System.Nullable<long> _GenderId;
		
		private System.Data.Linq.Binary _Pic;
		
		private System.Nullable<long> _CurrentStatus;
		
		private string _PicPath;
		
		private System.Nullable<long> _YearId;
		
		private System.Nullable<long> _ActionTypeId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCNICChanging(string value);
    partial void OnCNICChanged();
    partial void OnFNameChanging(string value);
    partial void OnFNameChanged();
    partial void OnDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnStudyClassIdChanging(System.Nullable<long> value);
    partial void OnStudyClassIdChanged();
    partial void OnAdmissionClassIdChanging(System.Nullable<long> value);
    partial void OnAdmissionClassIdChanged();
    partial void OnSecIdChanging(System.Nullable<long> value);
    partial void OnSecIdChanged();
    partial void OnRemarksChanging(string value);
    partial void OnRemarksChanged();
    partial void OnGuardianNameChanging(string value);
    partial void OnGuardianNameChanged();
    partial void OnGuardianRelationIdChanging(System.Nullable<long> value);
    partial void OnGuardianRelationIdChanged();
    partial void OnGRNoChanging(string value);
    partial void OnGRNoChanged();
    partial void OnReligionIdChanging(System.Nullable<long> value);
    partial void OnReligionIdChanged();
    partial void OnCasteIdChanging(System.Nullable<long> value);
    partial void OnCasteIdChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnPlaceOBCityIdChanging(System.Nullable<long> value);
    partial void OnPlaceOBCityIdChanged();
    partial void OnLastSchoolIdChanging(System.Nullable<long> value);
    partial void OnLastSchoolIdChanged();
    partial void OnProfessionIdChanging(System.Nullable<long> value);
    partial void OnProfessionIdChanged();
    partial void OnPermAdressChanging(string value);
    partial void OnPermAdressChanged();
    partial void OnPermMobileNoChanging(string value);
    partial void OnPermMobileNoChanged();
    partial void OnPermPhoneNoChanging(string value);
    partial void OnPermPhoneNoChanged();
    partial void OnPresentAddressChanging(string value);
    partial void OnPresentAddressChanged();
    partial void OnPresentMobileNoChanging(string value);
    partial void OnPresentMobileNoChanged();
    partial void OnPresentPhoneNoChanging(string value);
    partial void OnPresentPhoneNoChanged();
    partial void OnOfficeAddressChanging(string value);
    partial void OnOfficeAddressChanged();
    partial void OnOfficeMobileNoChanging(string value);
    partial void OnOfficeMobileNoChanged();
    partial void OnOfficePhoneNoChanging(string value);
    partial void OnOfficePhoneNoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnRollNoChanging(string value);
    partial void OnRollNoChanged();
    partial void OnGenderIdChanging(System.Nullable<long> value);
    partial void OnGenderIdChanged();
    partial void OnPicChanging(System.Data.Linq.Binary value);
    partial void OnPicChanged();
    partial void OnCurrentStatusChanging(System.Nullable<long> value);
    partial void OnCurrentStatusChanged();
    partial void OnPicPathChanging(string value);
    partial void OnPicPathChanged();
    partial void OnYearIdChanging(System.Nullable<long> value);
    partial void OnYearIdChanged();
    partial void OnActionTypeIdChanging(System.Nullable<long> value);
    partial void OnActionTypeIdChanged();
    #endregion
		
		public Student_Profile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNIC", DbType="VarChar(50)")]
		public string CNIC
		{
			get
			{
				return this._CNIC;
			}
			set
			{
				if ((this._CNIC != value))
				{
					this.OnCNICChanging(value);
					this.SendPropertyChanging();
					this._CNIC = value;
					this.SendPropertyChanged("CNIC");
					this.OnCNICChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="VarChar(50)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this.OnFNameChanging(value);
					this.SendPropertyChanging();
					this._FName = value;
					this.SendPropertyChanged("FName");
					this.OnFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTime
		{
			get
			{
				return this._DateTime;
			}
			set
			{
				if ((this._DateTime != value))
				{
					this.OnDateTimeChanging(value);
					this.SendPropertyChanging();
					this._DateTime = value;
					this.SendPropertyChanged("DateTime");
					this.OnDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudyClassId", DbType="BigInt")]
		public System.Nullable<long> StudyClassId
		{
			get
			{
				return this._StudyClassId;
			}
			set
			{
				if ((this._StudyClassId != value))
				{
					this.OnStudyClassIdChanging(value);
					this.SendPropertyChanging();
					this._StudyClassId = value;
					this.SendPropertyChanged("StudyClassId");
					this.OnStudyClassIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdmissionClassId", DbType="BigInt")]
		public System.Nullable<long> AdmissionClassId
		{
			get
			{
				return this._AdmissionClassId;
			}
			set
			{
				if ((this._AdmissionClassId != value))
				{
					this.OnAdmissionClassIdChanging(value);
					this.SendPropertyChanging();
					this._AdmissionClassId = value;
					this.SendPropertyChanged("AdmissionClassId");
					this.OnAdmissionClassIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecId", DbType="BigInt")]
		public System.Nullable<long> SecId
		{
			get
			{
				return this._SecId;
			}
			set
			{
				if ((this._SecId != value))
				{
					this.OnSecIdChanging(value);
					this.SendPropertyChanging();
					this._SecId = value;
					this.SendPropertyChanged("SecId");
					this.OnSecIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="VarChar(MAX)")]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this.OnRemarksChanging(value);
					this.SendPropertyChanging();
					this._Remarks = value;
					this.SendPropertyChanged("Remarks");
					this.OnRemarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuardianName", DbType="VarChar(50)")]
		public string GuardianName
		{
			get
			{
				return this._GuardianName;
			}
			set
			{
				if ((this._GuardianName != value))
				{
					this.OnGuardianNameChanging(value);
					this.SendPropertyChanging();
					this._GuardianName = value;
					this.SendPropertyChanged("GuardianName");
					this.OnGuardianNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuardianRelationId", DbType="BigInt")]
		public System.Nullable<long> GuardianRelationId
		{
			get
			{
				return this._GuardianRelationId;
			}
			set
			{
				if ((this._GuardianRelationId != value))
				{
					this.OnGuardianRelationIdChanging(value);
					this.SendPropertyChanging();
					this._GuardianRelationId = value;
					this.SendPropertyChanged("GuardianRelationId");
					this.OnGuardianRelationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRNo", DbType="VarChar(50)")]
		public string GRNo
		{
			get
			{
				return this._GRNo;
			}
			set
			{
				if ((this._GRNo != value))
				{
					this.OnGRNoChanging(value);
					this.SendPropertyChanging();
					this._GRNo = value;
					this.SendPropertyChanged("GRNo");
					this.OnGRNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReligionId", DbType="BigInt")]
		public System.Nullable<long> ReligionId
		{
			get
			{
				return this._ReligionId;
			}
			set
			{
				if ((this._ReligionId != value))
				{
					this.OnReligionIdChanging(value);
					this.SendPropertyChanging();
					this._ReligionId = value;
					this.SendPropertyChanged("ReligionId");
					this.OnReligionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CasteId", DbType="BigInt")]
		public System.Nullable<long> CasteId
		{
			get
			{
				return this._CasteId;
			}
			set
			{
				if ((this._CasteId != value))
				{
					this.OnCasteIdChanging(value);
					this.SendPropertyChanging();
					this._CasteId = value;
					this.SendPropertyChanged("CasteId");
					this.OnCasteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceOBCityId", DbType="BigInt")]
		public System.Nullable<long> PlaceOBCityId
		{
			get
			{
				return this._PlaceOBCityId;
			}
			set
			{
				if ((this._PlaceOBCityId != value))
				{
					this.OnPlaceOBCityIdChanging(value);
					this.SendPropertyChanging();
					this._PlaceOBCityId = value;
					this.SendPropertyChanged("PlaceOBCityId");
					this.OnPlaceOBCityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastSchoolId", DbType="BigInt")]
		public System.Nullable<long> LastSchoolId
		{
			get
			{
				return this._LastSchoolId;
			}
			set
			{
				if ((this._LastSchoolId != value))
				{
					this.OnLastSchoolIdChanging(value);
					this.SendPropertyChanging();
					this._LastSchoolId = value;
					this.SendPropertyChanged("LastSchoolId");
					this.OnLastSchoolIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfessionId", DbType="BigInt")]
		public System.Nullable<long> ProfessionId
		{
			get
			{
				return this._ProfessionId;
			}
			set
			{
				if ((this._ProfessionId != value))
				{
					this.OnProfessionIdChanging(value);
					this.SendPropertyChanging();
					this._ProfessionId = value;
					this.SendPropertyChanged("ProfessionId");
					this.OnProfessionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermAdress", DbType="VarChar(MAX)")]
		public string PermAdress
		{
			get
			{
				return this._PermAdress;
			}
			set
			{
				if ((this._PermAdress != value))
				{
					this.OnPermAdressChanging(value);
					this.SendPropertyChanging();
					this._PermAdress = value;
					this.SendPropertyChanged("PermAdress");
					this.OnPermAdressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermMobileNo", DbType="VarChar(50)")]
		public string PermMobileNo
		{
			get
			{
				return this._PermMobileNo;
			}
			set
			{
				if ((this._PermMobileNo != value))
				{
					this.OnPermMobileNoChanging(value);
					this.SendPropertyChanging();
					this._PermMobileNo = value;
					this.SendPropertyChanged("PermMobileNo");
					this.OnPermMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PermPhoneNo", DbType="VarChar(50)")]
		public string PermPhoneNo
		{
			get
			{
				return this._PermPhoneNo;
			}
			set
			{
				if ((this._PermPhoneNo != value))
				{
					this.OnPermPhoneNoChanging(value);
					this.SendPropertyChanging();
					this._PermPhoneNo = value;
					this.SendPropertyChanged("PermPhoneNo");
					this.OnPermPhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentAddress", DbType="VarChar(MAX)")]
		public string PresentAddress
		{
			get
			{
				return this._PresentAddress;
			}
			set
			{
				if ((this._PresentAddress != value))
				{
					this.OnPresentAddressChanging(value);
					this.SendPropertyChanging();
					this._PresentAddress = value;
					this.SendPropertyChanged("PresentAddress");
					this.OnPresentAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentMobileNo", DbType="VarChar(50)")]
		public string PresentMobileNo
		{
			get
			{
				return this._PresentMobileNo;
			}
			set
			{
				if ((this._PresentMobileNo != value))
				{
					this.OnPresentMobileNoChanging(value);
					this.SendPropertyChanging();
					this._PresentMobileNo = value;
					this.SendPropertyChanged("PresentMobileNo");
					this.OnPresentMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentPhoneNo", DbType="VarChar(50)")]
		public string PresentPhoneNo
		{
			get
			{
				return this._PresentPhoneNo;
			}
			set
			{
				if ((this._PresentPhoneNo != value))
				{
					this.OnPresentPhoneNoChanging(value);
					this.SendPropertyChanging();
					this._PresentPhoneNo = value;
					this.SendPropertyChanged("PresentPhoneNo");
					this.OnPresentPhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeAddress", DbType="VarChar(MAX)")]
		public string OfficeAddress
		{
			get
			{
				return this._OfficeAddress;
			}
			set
			{
				if ((this._OfficeAddress != value))
				{
					this.OnOfficeAddressChanging(value);
					this.SendPropertyChanging();
					this._OfficeAddress = value;
					this.SendPropertyChanged("OfficeAddress");
					this.OnOfficeAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeMobileNo", DbType="VarChar(50)")]
		public string OfficeMobileNo
		{
			get
			{
				return this._OfficeMobileNo;
			}
			set
			{
				if ((this._OfficeMobileNo != value))
				{
					this.OnOfficeMobileNoChanging(value);
					this.SendPropertyChanging();
					this._OfficeMobileNo = value;
					this.SendPropertyChanged("OfficeMobileNo");
					this.OnOfficeMobileNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficePhoneNo", DbType="VarChar(50)")]
		public string OfficePhoneNo
		{
			get
			{
				return this._OfficePhoneNo;
			}
			set
			{
				if ((this._OfficePhoneNo != value))
				{
					this.OnOfficePhoneNoChanging(value);
					this.SendPropertyChanging();
					this._OfficePhoneNo = value;
					this.SendPropertyChanged("OfficePhoneNo");
					this.OnOfficePhoneNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RollNo", DbType="VarChar(50)")]
		public string RollNo
		{
			get
			{
				return this._RollNo;
			}
			set
			{
				if ((this._RollNo != value))
				{
					this.OnRollNoChanging(value);
					this.SendPropertyChanging();
					this._RollNo = value;
					this.SendPropertyChanged("RollNo");
					this.OnRollNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GenderId", DbType="BigInt")]
		public System.Nullable<long> GenderId
		{
			get
			{
				return this._GenderId;
			}
			set
			{
				if ((this._GenderId != value))
				{
					this.OnGenderIdChanging(value);
					this.SendPropertyChanging();
					this._GenderId = value;
					this.SendPropertyChanged("GenderId");
					this.OnGenderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pic", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Pic
		{
			get
			{
				return this._Pic;
			}
			set
			{
				if ((this._Pic != value))
				{
					this.OnPicChanging(value);
					this.SendPropertyChanging();
					this._Pic = value;
					this.SendPropertyChanged("Pic");
					this.OnPicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentStatus", DbType="BigInt")]
		public System.Nullable<long> CurrentStatus
		{
			get
			{
				return this._CurrentStatus;
			}
			set
			{
				if ((this._CurrentStatus != value))
				{
					this.OnCurrentStatusChanging(value);
					this.SendPropertyChanging();
					this._CurrentStatus = value;
					this.SendPropertyChanged("CurrentStatus");
					this.OnCurrentStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicPath", DbType="VarChar(MAX)")]
		public string PicPath
		{
			get
			{
				return this._PicPath;
			}
			set
			{
				if ((this._PicPath != value))
				{
					this.OnPicPathChanging(value);
					this.SendPropertyChanging();
					this._PicPath = value;
					this.SendPropertyChanged("PicPath");
					this.OnPicPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearId", DbType="BigInt")]
		public System.Nullable<long> YearId
		{
			get
			{
				return this._YearId;
			}
			set
			{
				if ((this._YearId != value))
				{
					this.OnYearIdChanging(value);
					this.SendPropertyChanging();
					this._YearId = value;
					this.SendPropertyChanged("YearId");
					this.OnYearIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionTypeId", DbType="BigInt")]
		public System.Nullable<long> ActionTypeId
		{
			get
			{
				return this._ActionTypeId;
			}
			set
			{
				if ((this._ActionTypeId != value))
				{
					this.OnActionTypeIdChanging(value);
					this.SendPropertyChanging();
					this._ActionTypeId = value;
					this.SendPropertyChanged("ActionTypeId");
					this.OnActionTypeIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fees_Open")]
	public partial class Fees_Open : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Id;
		
		private System.Nullable<long> _FeeId;
		
		private System.Nullable<long> _StId;
		
		private System.Nullable<decimal> _OpeningAmount;
		
		private System.Nullable<int> _CurrentStatusId;
		
		private System.DateTime _ActionDate;
		
		private string _Description;
		
		private System.Nullable<long> _YearId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnFeeIdChanging(System.Nullable<long> value);
    partial void OnFeeIdChanged();
    partial void OnStIdChanging(System.Nullable<long> value);
    partial void OnStIdChanged();
    partial void OnOpeningAmountChanging(System.Nullable<decimal> value);
    partial void OnOpeningAmountChanged();
    partial void OnCurrentStatusIdChanging(System.Nullable<int> value);
    partial void OnCurrentStatusIdChanged();
    partial void OnActionDateChanging(System.DateTime value);
    partial void OnActionDateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnYearIdChanging(System.Nullable<long> value);
    partial void OnYearIdChanged();
    #endregion
		
		public Fees_Open()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FeeId", DbType="BigInt")]
		public System.Nullable<long> FeeId
		{
			get
			{
				return this._FeeId;
			}
			set
			{
				if ((this._FeeId != value))
				{
					this.OnFeeIdChanging(value);
					this.SendPropertyChanging();
					this._FeeId = value;
					this.SendPropertyChanged("FeeId");
					this.OnFeeIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StId", DbType="BigInt")]
		public System.Nullable<long> StId
		{
			get
			{
				return this._StId;
			}
			set
			{
				if ((this._StId != value))
				{
					this.OnStIdChanging(value);
					this.SendPropertyChanging();
					this._StId = value;
					this.SendPropertyChanged("StId");
					this.OnStIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpeningAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> OpeningAmount
		{
			get
			{
				return this._OpeningAmount;
			}
			set
			{
				if ((this._OpeningAmount != value))
				{
					this.OnOpeningAmountChanging(value);
					this.SendPropertyChanging();
					this._OpeningAmount = value;
					this.SendPropertyChanged("OpeningAmount");
					this.OnOpeningAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentStatusId", DbType="Int")]
		public System.Nullable<int> CurrentStatusId
		{
			get
			{
				return this._CurrentStatusId;
			}
			set
			{
				if ((this._CurrentStatusId != value))
				{
					this.OnCurrentStatusIdChanging(value);
					this.SendPropertyChanging();
					this._CurrentStatusId = value;
					this.SendPropertyChanged("CurrentStatusId");
					this.OnCurrentStatusIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActionDate", DbType="DateTime NOT NULL")]
		public System.DateTime ActionDate
		{
			get
			{
				return this._ActionDate;
			}
			set
			{
				if ((this._ActionDate != value))
				{
					this.OnActionDateChanging(value);
					this.SendPropertyChanging();
					this._ActionDate = value;
					this.SendPropertyChanged("ActionDate");
					this.OnActionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YearId", DbType="BigInt")]
		public System.Nullable<long> YearId
		{
			get
			{
				return this._YearId;
			}
			set
			{
				if ((this._YearId != value))
				{
					this.OnYearIdChanging(value);
					this.SendPropertyChanging();
					this._YearId = value;
					this.SendPropertyChanged("YearId");
					this.OnYearIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
